version: "3"
services:
  api:
    container_name: alaska-test
    volumes:
      - "./source:/deploy/source"
    image: alaska-back
    ports:
     - "5000:5000"
    links:
      - alaska-database

  database:
    image: mongo:3.0.2
    ports:
      - "27088:27017"
    volumes:
      - "/mongo/db/data:/data/db"
